import groovy.transform.CompileStatic
import groovy.transform.PackageScope
import javax.inject.Inject

pluginManager.apply(OsgiPublishPluginImpl)

@CompileStatic
@PackageScope
final class OsgiPublishPluginImpl implements Plugin<Project> {
    private final SoftwareComponentFactory factory

    @Inject
    OsgiPublishPluginImpl(SoftwareComponentFactory factory) {
        this.factory = factory
    }

    @Override
    void apply(Project project) {
        project.components.add(factory.adhoc('osgi'))
    }
}

