import aQute.bnd.gradle.Bundle
import aQute.bnd.version.MavenVersion
import aQute.bnd.header.OSGiHeader
import java.util.jar.JarFile
import java.util.jar.Manifest
import static org.gradle.jvm.toolchain.JavaLanguageVersion.of

plugins {
    id 'com.jfrog.artifactory'
    id 'org.javamodularity.moduleplugin'
    id 'com.github.johnrengelman.shadow'
    id 'com.dorongold.task-tree'
    id 'biz.aQute.bnd.builder' apply false
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'org.javamodularity.moduleplugin'

    java {
        toolchain {
            languageVersion = of(testJavaVersion)

            // Configure Gradle to use IBM J9 JDK toolchain.
            // (You will need to install J9 manually first.)
            //vendor = JvmVendorSpec.IBM
            //implementation = JvmImplementation.J9
        }
        withSourcesJar()
        withJavadocJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = targetJavaVersion.toInteger()
    }

    tasks.withType(GenerateModuleMetadata).configureEach {
        enabled = false
    }

    group               = "co.paralleluniverse"
    version             = quasarVersion
    status              = "integration"
    description         = "Fibers, Channels and Actors for the JVM"
    ext.url             = "http://puniverse.github.com/quasar"
    ext.vendor          = "Parallel Universe Software Co."
    ext.licenseName1    = "The GNU Lesser General Public License, version 3"
    ext.licenseUrl1     = "http://www.gnu.org/licenses/lgpl-3.0.txt"
    ext.licenseName2    = "Eclipse Public License - v 1.0"
    ext.licenseUrl2     = "http://www.eclipse.org/legal/epl-v10.html"
    ext.scmUrl          = "https://github.com/corda/quasar"
    ext.scmConnection   = "https://github.com/corda/quasar.git"
    ext.distDir         = "$buildDir/dist"
    ext.isReleaseVersion = !version.endsWith("SNAPSHOT")
    ext.baselib         = "${rootProject.projectDir}/baselib"
    ext.quasarJar = "${rootDir}/quasar-core/build/libs/quasar-core-${version}.jar" // project(':quasar-core').jar.archivePath

    if (!project.hasProperty('mainClass')) { // must use project.hasProperty() rather than hasProperty in subprojects (gradle bug)
        ext.mainClass = ''
    }

    repositories {
        flatDir {
            dirs baselib
        }
        repositories {
            mavenLocal()
            mavenCentral()
            maven { url 'https://repository.ow2.org/nexus/content/repositories/snapshots' }
            maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
        }
    }

    configurations.configureEach {
        resolutionStrategy {
            dependencySubstitution {
                // Kryo demands Objenesis 3.3, but Mockito wants Objenesis 2.6
                substitute module('org.objenesis:objenesis') using module("org.objenesis:objenesis:3.3")

                // Avoid problem when DropWizard and Log4J ask for different versions of SLF4J.
                substitute module('org.slf4j:slf4j-api') using module("org.slf4j:slf4j-api:$slf4jVersion")
            }
        }
    }

    configurations {
        provided {
            canBeConsumed = false
        }
        timewarp {
            canBeConsumed = false
        }

        compileOnly.extendsFrom provided
        testCompileOnly.extendsFrom compileOnly
        testRuntimeOnly.extendsFrom provided
    }

    sourceSets {
        main {
            output.dir "$buildDir/generated-resources/main", builtBy: 'compileJava'
        }
        jmh {
            compileClasspath += files(main.compileClasspath, main.output, test.compileClasspath, test.output)
            runtimeClasspath += files(compileClasspath, main.runtimeClasspath, test.runtimeClasspath)
        }
    }

    dependencies {
        constraints {
            compileOnly('org.osgi:osgi.annotation') {
                version {
                    strictly osgiAnnotationVersion
                }
            }
            compileOnly('org.osgi:osgi.core') {
                version {
                    strictly osgiCoreVersion
                }
            }
            compileOnly('org.osgi:org.osgi.service.component.annotations') {
                version {
                    strictly osgiServiceComponentVersion
                }
            }
        }

        provided "org.apache.ant:ant:1.10.5"
        timewarp 'co.paralleluniverse:timewarp:0.2.0-SNAPSHOT'
        testImplementation 'junit:junit:4.13.2'
        testImplementation "org.assertj:assertj-core:$assertjVersion"
        testImplementation('com.google.truth:truth:0.42') {
            exclude group: 'com.google.guava', module: 'guava'
            exclude group: 'com.google.errorprone', module: '*'
            exclude group: 'junit', module: 'junit'
        }
        testImplementation("org.mockito:mockito-core:2.23.0") {
            exclude group: "org.ow2.asm", module: '*'
            exclude group: "net.bytebuddy", module: '*'
        }
        testRuntimeOnly "net.bytebuddy:byte-buddy:1.9.2" // for Mockito
        testRuntimeOnly("com.google.guava:guava:$guavaVersion") {
            exclude group: 'com.google.errorprone', module: '*'
            exclude group: 'org.checkerframework', module: 'checker-qual'
        }

        jmhImplementation 'org.openjdk.jmh:jmh-core:1.21'
        jmhImplementation 'org.openjdk.jmh:jmh-generator-annprocess:1.21'

        annotationProcessor 'org.kohsuke.metainf-services:metainf-services:1.8'
        // annotationProcessor 'com.google.auto.service:auto-service:1.0-rc1' // same as metainf-services
        // markdownDoclet "ch.raffael.pegdown-doclet:pegdown-doclet:1.1.1"
    }

    tasks.named('compileJava', JavaCompile) {
        dependsOn tasks.named('processResources')
        if (project.name != 'quasar-kotlin' && !project.name.contains('osgi')) {
            doLast {
                scanAndInstrument(sourceSets.main, [configurations.provided, configurations.runtimeClasspath])
            }
        }
    }

    tasks.named('sourcesJar', Jar) {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }

    tasks.named('test', Test) {
        dependsOn tasks.named('jar', Jar)

        // Quasar needs reflective access to these packages.
        jvmArgs '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
                '--add-opens', 'java.base/java.lang.invoke=ALL-UNNAMED',
                '--add-opens', 'java.base/java.time=ALL-UNNAMED',
                '--add-opens', 'java.base/java.util=ALL-UNNAMED'
                '--illegal-access=warn'
    }

    tasks.withType(Test).configureEach {
        useJUnit()

        if (project.name != 'quasar-kotlin'
              && project.name != 'kryo-serializers'
              && !project.name.contains('osgi')) {
            moduleOptions {
                runOnClasspath = true
            }
        }
        // jvmArgs '--add-opens', 'java.base/java.lang=ALL-UNNAMED'
        // systemProperty 'co.paralleluniverse.fibers.verifyInstrumentation', 'true'

        // systemProperty "java.util.logging.config.file", "jul.properties"

        // Uncomment and add ${rootProject.projectDir}/log4j.xml, if not present, for logging
        // systemProperty "log4j.configurationFile", "${rootProject.projectDir}/log4j.xml"

        // systemProperty "Log4jContextSelector", "org.apache.logging.log4j.core.async.AsyncLoggerContextSelector"

        // systemProperty 'co.paralleluniverse.debugMode', 'true'
        systemProperty 'co.paralleluniverse.monitoring.flightRecorderLevel', '5'
        systemProperty 'co.paralleluniverse.globalFlightRecorder', 'true'
        systemProperty 'co.paralleluniverse.flightRecorderDumpFile', 'quasar.log'
        systemProperty 'co.paralleluniverse.monitoring.flightRecorderSize', '200000'

        if (project.name != 'quasar-core') {
            jvmArgs "-javaagent:${quasarJar}" // =vdmc (verbose, debug, allow monitors, check class)
        }

        if (!project.name.contains('kotlin')) { // TODO investigate why kotlin-plugin 1.1.2+ doesn't like it
            jvmArgs "-Xbootclasspath/a:${configurations.timewarp.singleFile}"
            if (System.getenv("TRAVIS") == 'true') {
                jvmArgs "-javaagent:${configurations.timewarp.singleFile}=3" // slow clock down x3
            }
        }

        jvmArgs "-Xmx1024m"
//        jvmArgs "-XX:+TraceClassLoading"
//        jvmArgs "-XX:+TraceClassUnloading"
//        if (!project.ext.java8) {
//            jvmArgs "-XX:MaxPermSize=512m" // Travis is having some trouble with PermGen
//        }
        // jvmArgs "-XX:-UseCompressedOops"

        beforeTest { desc ->
            logger.quiet("Running test: {}", desc)
        }

        afterTest { desc, result ->
            if(result.resultType == TestResult.ResultType.FAILURE) {
                logger.quiet("Failed test ${desc.name} [${desc.className}] with exception: ${result.exception}")
                if(result.exception != null) {
                    result.exception.printStackTrace()
                }
            }
        }

        doLast() {
            println "file://" + reports.html.outputLocation.file('/index.html').get()
        }
    }

    ['run', 'debug'].each { name ->
        project.task(name, type: JavaExec, dependsOn:[testClasses]) {
            classpath = sourceSets.main.runtimeClasspath
            if(project.hasProperty('mainClass')){
                mainClass = project.mainClass
            }
            if(project.hasProperty('args')){
                args project.args.split('\\s+')
            }

            jvmArgs '-Xmx2048m'
            // jvmArgs "-Xbootclasspath/p:${System.getProperty("user.home")}/jsr166.jar"
            // systemProperty 'co.paralleluniverse.fibers.DefaultFiberPool.parallelism', '1'

            systemProperty "log4j.configurationFile", "${rootProject.projectDir}/log4j.xml"
            systemProperty "Log4jContextSelector", "org.apache.logging.log4j.core.async.AsyncLoggerContextSelector"
            // systemProperty 'co.paralleluniverse.fibers.verifyInstrumentation', 'true'
            jvmArgs "-javaagent:${quasarJar}" // =vdmc (verbose, debug, allow monitors, check class)

            // jvmArgs '-XX:+UnlockCommercialFeatures', '-XX:+FlightRecorder', '-XX:StartFlightRecording=duration=60s,filename=recording.jfr,settings=heap'
        }
    }
    debug.debug = true

    project.afterEvaluate {
        tasks.named('run') {
            dependsOn project(':quasar-core').tasks.named('classicJar')
        }

        tasks.named('jar', Jar) {
            manifest {
                attributes(
                    "Implementation-Title"      :   project.name,
                    "Implementation-Version"    :   archiveVersion.get(),
                    "Implementation-Vendor"     :   vendor,
                    "Built-By"                  :   System.getProperty("user.name"),
                )
            }
        }
    }

    tasks.withType(JavaExec).configureEach {
        classpath += files(sourceSets.test.runtimeClasspath, sourceSets.test.output, sourceSets.jmh.runtimeClasspath, sourceSets.jmh.output)
    }

    //    tasks.withType(Debug) {
    //        classpath = sourceSets.test.runtimeClasspath
    //    }

    javadoc {
        classpath += configurations.provided
        options {
            addStringOption('Xdoclint:none', '-quiet')
        }
    }

    defaultTasks 'build'

    task artifacts {
        group = "Help"
        description = "Displays the artifacts associated with each configuration of " + project
        doFirst {
            configurations.findAll().each { config ->
                println "${config}:"
                // config.allArtifacts.each { file -> println "--- " + file }
                config.allArtifacts.getFiles().each { file -> println "" + file }
                println ' '
            }
        }
    }
}

logger.lifecycle("Gradle version: {}", gradle.gradleVersion)
logger.lifecycle("Java version: {}", JavaVersion.current())
logger.lifecycle("Java source compatibility: {}", sourceCompatibility)
logger.lifecycle("Java target compatibility: {}", targetCompatibility)
logger.lifecycle("Kotlin version: {}", kotlinVersion)
logger.lifecycle("Building quasar version: {}", quasarVersion)

def scanAndInstrument(SourceSet sset, configs) {

    def cp = sset.output.classesDirs.getAsPath() + ':' + sset.output.resourcesDir + ':' + configs*.asPath.join(':')
    def suspendableSupersFile = "${sset.output.dirs.singleFile}/META-INF/suspendable-supers"

    // ENT-5598 quasar-kotlin has two output directories, java and kotlin.
    // So we have to cope with multiple directories in classesDirs.

    ant.delete(file: suspendableSupersFile)
    ant.taskdef(
            name:'scanSuspendables',
            classname:'co.paralleluniverse.fibers.instrument.SuspendablesScanner',
            classpath: cp)
    ant.scanSuspendables(
            auto: false,
            supersFile: suspendableSupersFile,
            append: true) {
        for (File f : sset.output.classesDirs) {
            fileset(dir: f)
        }
    }

    ant.taskdef(
            name:'instrumentation',
            classname:'co.paralleluniverse.fibers.instrument.InstrumentationTask',
            classpath: cp)
    ant.instrumentation(verbose: true, check: true, debug: true) {
        for (File f : sset.output.classesDirs) {
            fileset(dir: f) {
                exclude(name: 'co/paralleluniverse/fibers/instrument/**/*.class')
            }
        }
    }

    // Filter out the 'requires org.objectweb.asm' from quasar-core's module-info, as it will be shadowed into the jar
    ant.taskdef(name:'filterModules', classname:'co.paralleluniverse.fibers.instrument.ModuleFilterTask', classpath: cp)
    ant.filterModules(module: 'org.objectweb.asm') {
        for (File f : sset.output.classesDirs) {
            fileset(dir: f)
        }
    }
}

static boolean containsOnly(String values, Iterable<String> expected) {
    expected.containsAll(parsePackages(values))
}

static Collection<String> removeOSGiFramework(Iterable<String> packages) {
    def osgiFramework = 'org.osgi.framework'
    packages.findAll { !it.startsWith(osgiFramework) || (it.length() > osgiFramework.length() && it[osgiFramework.length()] != '.') }
}

static Set<String> parsePackages(String values) {
    OSGiHeader.parseHeader(values).keySet().findAll { !it.startsWith('java.') }
}

static String fetchManifestAttributeFrom(File archive, String attributeName) {
    return new JarFile(archive).withCloseable { jar ->
        Manifest manifest = jar.manifest
        manifest.mainAttributes.getValue(attributeName)
    }
}

static String fetchManifestAttributeFrom(TaskProvider<? extends Jar> task, String attributeName) {
    return fetchManifestAttributeFrom(task.flatMap { it.archiveFile }.get().asFile, attributeName)
}

static String fetchVersionOf(Configuration configuration, String groupName, String artifactName) {
    def versions = new HashSet<String>()
    configuration.resolvedConfiguration.resolvedArtifacts.forEach {
        def id = it.moduleVersion.id
        if (id.group == groupName && id.name == artifactName) {
            versions += id.version
        }
    }
    if (versions.size() != 1) {
        throw new IllegalStateException("Multiple versions of $groupName:$artifactName found in ${configuration.name}")
    }
    return versions.first()
}

project (':quasar-core') {
    /*
     * see:
     *   https://docs.gradle.org/current/userguide/java_plugin.html
     *   http://examples.javacodegeeks.com/core-java/gradle/gradle-sourcesets-example/
     *   http://stackoverflow.com/questions/15870662/gradle-create-a-new-jar-from-each-sourceset
     *   http://stackoverflow.com/questions/18190614/compiling-a-project-with-different-java-source-compatibility
     *   https://softnoise.wordpress.com/2014/09/07/gradle-sub-project-test-dependencies-in-multi-project-builds/
     */

    apply plugin: 'com.github.johnrengelman.shadow'
    apply plugin: 'osgi-publish'

    ext.moduleName = 'co.paralleluniverse.quasar.core'

    sourceSets {
        main {
            java {
                srcDir 'src/main/java'
            }
        }
        core {
            java {
                srcDir 'src/main/core'
            }
            compileClasspath += main.compileClasspath
        }
        frameworkExtension {
            java {
                srcDir 'src/main/frameworkExtension'
            }
            resources {
                srcDir 'src/main/frameworkExtensionResources'
            }
            compileClasspath += main.compileClasspath
        }

        test {
            java {
                srcDir 'src/test/java'
            }
        }

        jmh {
            java {
                srcDir 'src/jmh/java'
            }

            compileClasspath += files(main.output, test.compileClasspath, test.output)
            runtimeClasspath += files(compileClasspath, test.runtimeClasspath)
        }

        classloadertest {
            java {
                srcDir 'src/classloadertest/java'
            }

            compileClasspath += files(main.output, test.output, test.compileClasspath)
            runtimeClasspath += files(compileClasspath, test.runtimeClasspath)
        }
    }

    configurations {
        classic {
            extendsFrom runtimeClasspath
            canBeResolved = false
        }
        frameworkExtension {
            canBeResolved = false
        }
        core {
            extendsFrom runtimeClasspath
            canBeResolved = false
        }

        frameworkExtensionCompileOnly {
            extendsFrom compileOnly
        }
        coreImplementation {
            extendsFrom implementation
            extendsFrom frameworkExtensionImplementation
        }

        testArtifacts {
            extendsFrom testRuntimeClasspath
            canBeResolved = false
        }
    }

    dependencies {
        implementation "io.dropwizard.metrics:metrics-core:$dropWizardVersion"
        implementation "io.dropwizard.metrics:metrics-jmx:$dropWizardVersion"
        implementation "org.hdrhistogram:HdrHistogram:2.1.10"
        implementation("org.latencyutils:LatencyUtils:2.0.3") {
            exclude group: "org.hdrhistogram", module: '*'
        }
        provided "org.ow2.asm:asm:$asmVersion"
        provided "org.ow2.asm:asm-analysis:$asmVersion"
        provided "org.ow2.asm:asm-commons:$asmVersion"
        provided "org.ow2.asm:asm-util:$asmVersion"

        implementation "com.esotericsoftware:kryo:$kryoVersion"
        implementation "de.javakaffee:kryo-serializers:$kryoSerializersVersion"

        compileOnly 'org.osgi:osgi.annotation'
        compileOnly 'org.osgi:osgi.core'

        coreImplementation files(sourceSets.frameworkExtension.output) {
            builtBy tasks.named('compileFrameworkExtensionJava', JavaCompile)
        }
        frameworkExtensionImplementation files(sourceSets.main.output) {
            builtBy tasks.named('compileJava', JavaCompile)
        }
    }

    tasks.named('compileFrameworkExtensionJava', JavaCompile) {
        doFirst {
            options.compilerArgs += [
                '--patch-module', "${project.moduleName}.framework.extension=${sourceSets.main.output.asPath}",
                '--module-path', configurations.frameworkExtensionCompileClasspath.asPath,
                '--module-version', project.version
            ]
        }
    }

    tasks.named('compileCoreJava', JavaCompile) {
        doFirst {
            options.compilerArgs += [
                '--patch-module', "${project.moduleName}.osgi=${sourceSets.main.output.asPath}",
                '--module-path', configurations.coreCompileClasspath.asPath,
                '--module-version', project.version
            ]
        }
    }

    // this happens after we've filtered the dependency on ASM from core's module-info
    tasks.matching { it.name == 'compileJava' || it.name == 'compileTestJava' }.configureEach {
        options.compilerArgs += [
            '--add-modules', 'org.objectweb.asm',
            '--add-modules', 'org.objectweb.asm.util',
            '--add-modules', 'org.objectweb.asm.commons',
            '--add-modules', 'org.objectweb.asm.tree.analysis',
            '--add-reads', 'co.paralleluniverse.quasar.core=org.objectweb.asm',
            '--add-reads', 'co.paralleluniverse.quasar.core=org.objectweb.asm.util',
            '--add-reads', 'co.paralleluniverse.quasar.core=org.objectweb.asm.commons',
            '--add-reads', 'co.paralleluniverse.quasar.core=org.objectweb.asm.tree.analysis'
        ]
    }

    tasks.named('jar', Jar) {
        archiveClassifier = 'ignore'
        enabled = false
    }

    def testJar = tasks.register('testJar', Jar) {
        archiveClassifier = 'tests'
        from(sourceSets.test.output) {
            // JPMS refuses to split packages across jars.
            include 'co/paralleluniverse/common/test/**'
        }
    }

    def shadowJar = tasks.named('shadowJar', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
        destinationDirectory = layout.buildDirectory.dir('libs')
        archiveClassifier = 'shadow'

        from sourceSets.main.output

        configurations = [project.configurations.compileClasspath]
        dependencies {
            include(dependency('org.ow2.asm:.*:.*'))
        }
        excludes.remove('module-info.class')

        relocate 'org.objectweb.asm.', 'co.paralleluniverse.asm.'
    }

    def shadowFiles = zipTree(shadowJar.flatMap { it.archiveFile })
    def classicJar = tasks.register('classicJar', Jar) {
        dependsOn shadowJar
        archiveClassifier = ''
        from(shadowFiles) {
            exclude 'co/paralleluniverse/fibers/instrument/QuasarActivator*'
            exclude 'co/paralleluniverse/fibers/instrument/QuasarBundleTracker*'
            exclude 'co/paralleluniverse/fibers/instrument/QuasarPermission*'
            exclude 'co/paralleluniverse/fibers/instrument/QuasarWeavingHook*'
        }

        manifest {
            attributes(
                "Implementation-Title"      :   project.name,
                "Implementation-Version"    :   archiveVersion.get(),
                "Implementation-Vendor"     :   vendor,
                "Premain-Class"             :   "co.paralleluniverse.fibers.instrument.JavaAgent",
                "Agent-Class"               :   "co.paralleluniverse.fibers.instrument.JavaAgent",
                "Can-Retransform-Classes"   :   "true",
                "Can-Redefine-Classes"      :   "true",
                "Built-By"                  :   System.getProperty("user.name"),
            )
        }
    }

    // Dark Gradle Magic to select the correct jar for publication.
    components.java {
        withVariantsFromConfiguration(configurations.shadowRuntimeElements) {
            skip()
        }
        addVariantsFromConfiguration(configurations.classic) {
            mapToMavenScope('runtime')
        }
    }

    def coreBundle = tasks.register('coreBundle', Bundle) {
        dependsOn classicJar
        from(zipTree(classicJar.flatMap { it.archiveFile })) {
            exclude 'co/paralleluniverse/asm/**'
            exclude 'co/paralleluniverse/common/asm/**'
            exclude 'co/paralleluniverse/common/resource/**'
            exclude 'co/paralleluniverse/fibers/instrument/**'
            exclude 'co/paralleluniverse/fibers/suspend/**'
            exclude 'module-info.class'
        }
        from(sourceSets.core.output)
        archiveAppendix = 'osgi'

        bundle {
            bnd archiveVersion.map { "Implementation-Version: $it" }

            bnd """\
Built-By: ${System.getProperty("user.name")}
Bundle-SymbolicName: co.paralleluniverse.quasar-core
Bundle-Name: Quasar Fibers
Bundle-Version: \${project.version}
Implementation-Title: \${project.name}
Implementation-Vendor: \${project.vendor}
Import-Package: \
 org.LatencyUtils.*;resolution:=optional,\
 org.HdrHistogram.*;resolution:=optional,\
 *
"""
        }
    }

    def validateCoreBundle = tasks.register("validateCoreBundle") {
        dependsOn coreBundle
        doLast {
            String importPackages = fetchManifestAttributeFrom(coreBundle, 'Import-Package')
            if (importPackages && !parsePackages(importPackages).disjoint(['co.paralleluniverse.asm'])) {
                throw new InvalidUserCodeException("OSGi bundle should not import shaded ASM package: " + importPackages)
            }
        }
    }

    coreBundle.configure {
        it.finalizedBy validateCoreBundle
    }

    tasks.named('processFrameworkExtensionResources', ProcessResources) {
        filesMatching('**/framework-extension.properties') {
            expand([
                'reflectAsmVersion': """${ ->
                    MavenVersion.parseMavenString(
                        fetchVersionOf(configurations.runtimeClasspath, 'com.esotericsoftware', 'reflectasm')
                    ).getOSGiVersion().toString()
                }"""
            ])
        }
    }

    def frameworkExtensionBundle = tasks.register('frameworkExtensionBundle', Bundle) {
        dependsOn shadowJar
        from(shadowFiles) {
            exclude 'META-INF/suspendable*'
            include 'co/paralleluniverse/asm/**'
            include 'co/paralleluniverse/common/asm/**'
            include 'co/paralleluniverse/common/resource/**'
            include 'co/paralleluniverse/fibers/instrument/**'
            exclude 'co/paralleluniverse/fibers/instrument/JavaAgent*'
            exclude 'co/paralleluniverse/fibers/instrument/InstrumentationTask*'
            exclude 'co/paralleluniverse/fibers/instrument/InstrumentationTKB*'
            exclude 'co/paralleluniverse/fibers/instrument/ModuleFilterTask*'
            exclude 'co/paralleluniverse/fibers/instrument/OldSuspendablesScanner*'
            exclude 'co/paralleluniverse/fibers/instrument/SuspendablesScanner*'
            include 'co/paralleluniverse/fibers/suspend/**'
        }
        from(sourceSets.frameworkExtension.output)
        archiveAppendix = 'osgi'
        archiveClassifier = 'framework-extension'

        bundle {
            bnd archiveVersion.map { "Implementation-Version: $it" }

            bnd """\
-fixupmessages "Classes found in the wrong directory"; restrict:=error; is:=warning
Built-By: ${System.getProperty("user.name")}
Bundle-SymbolicName: co.paralleluniverse.quasar-core.framework.extension
Bundle-Name: Quasar Framework Extension
Bundle-Version: \${project.version}
Implementation-Title: \${project.name}
Implementation-Vendor: \${project.vendor}
"""
        }
    }

    def validateFrameworkExtensionBundle = tasks.register('validateFrameworkExtensionBundle') {
        dependsOn frameworkExtensionBundle
        doLast {
            def importPackagesAttr = fetchManifestAttributeFrom(frameworkExtensionBundle, 'Import-Package')
            def importPackages = removeOSGiFramework(parsePackages(importPackagesAttr))
            if (importPackages && !['co.paralleluniverse.common.resource', 'co.paralleluniverse.fibers.suspend', 'org.osgi.util.tracker'].containsAll(importPackages)) {
                throw new InvalidUserDataException("OSGi bundle for OSGi framework extension should only import from Java, OSGi framework or itself: " + importPackages)
            }
        }
    }

    frameworkExtensionBundle.configure {
        it.finalizedBy validateFrameworkExtensionBundle
    }

    tasks.named('test', Test) {
        dependsOn = [classicJar, coreBundle, frameworkExtensionBundle, compileClassloadertestJava]
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath

        doFirst {
            jvmArgs "-javaagent:${classicJar.flatMap { it.archiveFile }.get()}" // =vdc
        }
    }

    artifacts {
        classic classicJar
        archives classicJar
        core coreBundle
        archives coreBundle
        frameworkExtension frameworkExtensionBundle
        archives frameworkExtensionBundle
        testArtifacts testJar
    }

    check.dependsOn test

    tasks.withType(JavaExec).configureEach {
        classpath += files(sourceSets.test.runtimeClasspath, sourceSets.test.output)
    }
    run.dependsOn compileJava, testClasses

    javadoc {
        options.encoding = 'UTF-8'
        source = sourceSets.main.allJava
    }

    components.named('osgi') {
        addVariantsFromConfiguration(configurations.core) {
            mapToMavenScope('runtime')
        }
        addVariantsFromConfiguration(configurations.frameworkExtension) {
            mapToMavenScope('runtime')
        }
    }
}

project (':quasar-actors') {
    ext.moduleName = 'co.paralleluniverse.quasar.actors'
    
    dependencies {
        provided project(path: ':quasar-core', configuration: 'classic')
        // compile 'org.mutabilitydetector:MutabilityDetector:0.9.2'
        implementation "org.slf4j:slf4j-api:$slf4jVersion"
        implementation "net.bytebuddy:byte-buddy:$byteBuddyVersion"
        implementation ("com.google.guava:guava:$guavaVersion") {
            exclude group: 'com.google.errorprone', module: '*'
            exclude group: 'org.checkerframework', module: 'checker-qual'
        }

        testImplementation project(path: ':quasar-core', configuration: 'testArtifacts')
        testRuntimeOnly "org.apache.logging.log4j:log4j-slf4j-impl:$log4jVersion"
        testRuntimeOnly "org.apache.logging.log4j:log4j-api:$log4jVersion"
        testRuntimeOnly "org.apache.logging.log4j:log4j-core:$log4jVersion"
        testRuntimeOnly "com.lmax:disruptor:3.4.2" // required for log4j
    }
}

project (':quasar-reactive-streams') {
    ext.moduleName = 'co.paralleluniverse.quasar.reactivestreams'
    
    dependencies {
        provided project(path: ':quasar-core', configuration: 'classic')
        implementation "org.reactivestreams:reactive-streams:1.0.2"
        testImplementation("org.reactivestreams:reactive-streams-tck:1.0.2") {
            exclude group: "junit", module: "*"
            exclude group: "org.testng", module: "testng"
        }
        testImplementation("org.testng:testng:$testngVersion") {
            exclude group: "com.google.guava", module: "*"
            exclude group: "junit", module: "*"
        }
    }

    tasks.named('test', Test) {
        useTestNG()
    }
}

project (':quasar-disruptor') {
    ext.moduleName = 'co.paralleluniverse.quasar.disruptor'

    dependencies {
        provided project(path: ':quasar-core', configuration: 'classic')
        implementation "com.lmax:disruptor:3.4.2"
    }
}

javadoc {
    dependsOn subprojects.javadoc
    title = "Quasar ${project(':quasar-core').version}"
    destinationDir = file("docs/javadoc")

    source = project(':quasar-core').sourceSets.main.allJava
    source += project(':quasar-actors').sourceSets.main.allJava
    source += project(':quasar-reactive-streams').sourceSets.main.allJava

    classpath = files(subprojects.collect { project -> project.sourceSets.main.compileClasspath })

    options {
         addStringOption('Xdoclint:none')
    }
    excludes = [
        "module-info.java", // for now
        "co/paralleluniverse/actors/spi/**",
        "co/paralleluniverse/actors/ActorMonitor.java",
        "co/paralleluniverse/actors/GlobalRegistry.java",
        "co/paralleluniverse/actors/JMXActorMonitor.java",
        "co/paralleluniverse/actors/LifecycleListener.java",
        "co/paralleluniverse/actors/LifecycleListenerProxy.java",
        "co/paralleluniverse/actors/MutabilityTester.java",
        "co/paralleluniverse/actors/RemoteActorProxyFactoryService.java",
        "co/paralleluniverse/actors/RemoteActorRef.java",
        "co/paralleluniverse/actors/RemoteActorProxyFactory.java",
        "co/paralleluniverse/common/benchmark/**",
        "co/paralleluniverse/common/classloader/**",
        "co/paralleluniverse/common/logging/**",
        "co/paralleluniverse/common/monitoring/**",
        "co/paralleluniverse/common/reflection/**",
        "co/paralleluniverse/common/test/**",
        "co/paralleluniverse/common/util/**",
        "co/paralleluniverse/concurrent/forkjoin/**",
        "co/paralleluniverse/concurrent/util/**",
        "co/paralleluniverse/data/record/DynamicGeneratedRecord.java",
        "co/paralleluniverse/data/record/DynamicRecord.java",
        "co/paralleluniverse/fibers/DefaultFiberPool.java",
        "co/paralleluniverse/fibers/FibersMonitor.java",
        "co/paralleluniverse/fibers/FiberTimedScheduler.java",
        "co/paralleluniverse/fibers/Instrumented.java",
        "co/paralleluniverse/fibers/NoopFibersMonitor.java",
        "co/paralleluniverse/fibers/instrument/**",
        "co/paralleluniverse/io/serialization/**",
        "co/paralleluniverse/remote/**",
        "co/paralleluniverse/strands/channels/SelectActionImpl.java",
        "co/paralleluniverse/strands/channels/disruptor/**", // not ready
        "co/paralleluniverse/strands/queues/**",
    ]
}

clean {
    dependsOn subprojects.clean
    doLast() {
        delete 'docs/javadoc'
    }
}

def publishedProjects = subprojects - project(':quasar-osgi-tests').allprojects

configure(publishedProjects) { subproject ->
    apply plugin: 'maven-publish'
    apply plugin: 'com.jfrog.artifactory'

    tasks.register('install') {
        dependsOn tasks.named('publishToMavenLocal')
    }

    publishing {
        publications {
            configureEach {
                groupId subproject.group

                pom {
                    packaging = 'jar'
                    description = subproject.description
                    url = subproject.url

                    scm {
                        url = subproject.scmUrl
                        connection = subproject.scmConnection
                        developerConnection = subproject.scmConnection
                    }
                    licenses {
                        license {
                            name = subproject.licenseName1
                            url = subproject.licenseUrl1
                            distribution = 'repo'
                        }
                        license {
                            name = subproject.licenseName2
                            url = subproject.licenseUrl2
                            distribution = 'repo'
                        }
                    }
                    developers {
                        developer {
                            id = 'pron'
                            name = 'Ron Pressler'
                        }
                        developer {
                            id = 'R3'
                            name = 'R3'
                            email = 'dev@corda.net'
                        }
                    }
                }
                pom.withXml {
                    Node pomNode = asNode()
                    pomNode.dependencies.'*'.findAll() {
                        it.artifactId.text().startsWith('org.ow2.asm')
                    }.each() {
                        it.parent().remove(it)
                    }
                }
            }

            pluginManager.withPlugin('osgi-publish') {
                create(subproject.name + '-osgi', MavenPublication) {
                    artifactId subproject.name + '-osgi'
                    from components.osgi
                    alias true

                    pluginManager.withPlugin('java') {
                        artifact tasks.named('sourcesJar', Jar)
                        artifact tasks.named('javadocJar', Jar)
                    }

                    pom {
                        name = subproject.name + '-osgi'
                    }
                }
            }

            create(subproject.name, MavenPublication) {
                artifactId subproject.name

                pluginManager.withPlugin('java') {
                    from components.java
                }

                pom {
                    name = subproject.name
                }
            }
        }
    }
}

artifactory {
    publish {
        contextUrl = artifactoryContextUrl
        repository {
            repoKey = System.getenv('CORDA_ARTIFACTORY_REPOKEY') ?: 'corda-dependencies-dev'
            username = project.findProperty('cordaArtifactoryUsername') ?: System.getenv('CORDA_ARTIFACTORY_USERNAME') ?: System.getProperty('corda.artifactory.username')
            password = project.findProperty('cordaArtifactoryPassword') ?: System.getenv('CORDA_ARTIFACTORY_PASSWORD') ?: System.getProperty('corda.artifactory.password')
            maven = true
        }

        defaults {
            if (publishedProjects.contains(project)) {
                publications(project.name)
                publications(project.name + '-osgi')
            }
        }
    }
}

wrapper {
    gradleVersion = '8.1.1'
    distributionType = Wrapper.DistributionType.BIN
}
