quasarVersion=0.9.0_r3
kotlinVersion=1.8.21
taskTreeVersion=1.3.1
shadowVersion=8.1.1
artifactoryVersion=4.31.9
assertjVersion=3.22.0
bndVersion=6.4.0
modulepluginVersion=1.8.12

targetJavaVersion=11
testJavaVersion=17

kotlin.stdlib.default.dependency=false

asmVersion=9.5

felixVersion=7.0.5
felixConfigAdminVersion=1.9.26
felixLogVersion=1.2.6
felixScrVersion=2.2.6
felixSecurityVersion=2.8.4

byteBuddyVersion=1.14.2
dropWizardVersion=4.1.0
guavaVersion=30.1.1-jre
junitJupiterVersion=5.9.2
junitPlatformVersion=1.9.2
kryoVersion=5.5.0
kryoSerializersVersion=0.45
log4jVersion=2.20.0
osgiAnnotationVersion=8.1.0
osgiCoreVersion=8.0.0
osgiServiceComponentVersion=1.5.0
osgiTestJunit5Version=1.2.1
osgiUtilFunctionVersion=1.2.0
osgiUtilPromiseVersion=1.3.0
slf4jVersion=1.7.36
testngVersion=7.6.1

artifactoryContextUrl=https://software.r3.com/artifactory

org.gradle.jvmargs=-XX:+UseG1GC -Xmx1g -Dfile.encoding=UTF-8
org.gradle.java.installations.auto-download=false
org.gradle.caching=false
org.gradle.daemon=false
