import static org.gradle.api.JavaVersion.*

pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven {
            name "R3 Maven remote repositories"
            url "https://software.r3.com/artifactory/corda-remotes"
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username = System.getenv('CORDA_ARTIFACTORY_USERNAME')
                password = System.getenv('CORDA_ARTIFACTORY_PASSWORD')
            }
        }
    }

    plugins {
        id 'org.jetbrains.kotlin.jvm' version kotlinVersion
        id 'com.dorongold.task-tree' version taskTreeVersion
        id 'com.github.johnrengelman.shadow' version shadowVersion
        id 'com.jfrog.artifactory' version artifactoryVersion
        id 'biz.aQute.bnd.builder' version bndVersion
    }
}

include 'quasar-core'
include 'quasar-actors'
include 'quasar-reactive-streams'
include 'quasar-disruptor'
include 'quasar-kotlin'
