package co.paralleluniverse.fibers.osgi;

import co.paralleluniverse.fibers.instrument.function.ResourceLocator;
import org.osgi.framework.Bundle;
import org.osgi.framework.BundleContext;
import org.osgi.framework.BundleReference;
import org.osgi.framework.wiring.BundleCapability;
import org.osgi.framework.wiring.BundleWire;
import org.osgi.framework.wiring.BundleWiring;

import java.net.URL;
import java.util.List;
import java.util.Map;

import static co.paralleluniverse.common.resource.ClassLoaderUtil.getBestClassLoader;
import static org.osgi.framework.wiring.BundleRevision.PACKAGE_NAMESPACE;

/**
 * This class is not used directly because {@link ClassLoader#getSystemClassLoader()}
 * might not contain the OSGi Framework classes. We will create this class on demand
 * inside a dynamic classloader, if/when we discover which {@link ClassLoader} the OSGi
 * framework does exist inside.
 */
@SuppressWarnings("unused")
public final class BundleLocator {
    private static final String BUNDLE_PROTOCOL = "bundle";

    public static ResourceLocator getFindResourceOwnerMethod() {
        return BundleLocator::findResourceOwner;
    }

    private static ClassLoader findResourceOwner(ClassLoader cl, String resourceName, URL resource) {
        if (resource != null) {
            if (BUNDLE_PROTOCOL.equals(resource.getProtocol()) && (cl instanceof BundleReference)) {
                final Bundle bundle = ((BundleReference) cl).getBundle();
                final BundleWiring wiring = new WiringView(resourceName, resource).getBundleWiring(bundle);
                if (wiring != null) {
                    return wiring.getClassLoader();
                }
            } else {
                // Get the first classloader in the hierarchy that can provide this resource.
                return getBestClassLoader(cl, resourceName, resource);
            }
        }
        return cl;
    }

    private static final class WiringView {
        private final String resourceName;
        private final URL resource;

        WiringView(String resourceName, URL resource) {
            this.resourceName = resourceName;
            this.resource = resource;
        }

        BundleWiring getBundleWiring(Bundle bundle) {
            // The bundle:// URL format is specific to the OSGi container.
            // Assuming Felix's format, try to parse the bundle ID out.
            final long bundleId = parseFelixBundleId(resource);
            if (bundleId == bundle.getBundleId()) {
                // No work required! Just use the original classloader.
                return null;
            }

            // A bundle must be STARTING / ACTIVE / STOPPING to have a BundleContext.
            final BundleContext context = bundle.getBundleContext();
            if (context != null && bundleId != -1) {
                final Bundle targetBundle = context.getBundle(bundleId);
                if (targetBundle != null) {
                    return targetBundle.adapt(BundleWiring.class);
                }
            }

            // Fall back to examining the bundle wirings for our resource's package.
            final BundleWiring initialWiring = bundle.adapt(BundleWiring.class);
            return (initialWiring != null) ? fetchBundleWiringFor(initialWiring, getPackageName(resourceName)) : null;
        }

        private static BundleWiring fetchBundleWiringFor(BundleWiring bundleWiring, String packageName) {
            final List<BundleWire> requiredWires = bundleWiring.getRequiredWires(PACKAGE_NAMESPACE);
            for (BundleWire requiredWire : requiredWires) {
                final BundleCapability capability = requiredWire.getCapability();
                if (capability != null) {
                    final Map<String, Object> attributes = capability.getAttributes();
                    final Object wirePackage = attributes.get(PACKAGE_NAMESPACE);
                    if (packageName.equals(wirePackage)) {
                        return requiredWire.getProviderWiring();
                    }
                }
            }
            // We haven't gone anywhere, so keep this wiring.
            return bundleWiring;
        }

        /**
         * @param resource A bundle:// URL generated by the Felix OSGi framework.
         * @return bundleId for the bundle owning this resource, or -1 if no such bundle.
         */
        private static long parseFelixBundleId(URL resource) {
            // Felix creates bundle:// URLs using the following format:
            //     bundle://<revision-id>:<bundle-classpath-index>/<resource-path>
            // where:
            //     <revision-id> = <framework-uuid>_<bundle-id>.<bundle-revision>
            final String host = resource.getHost();
            final int startIdx = host.indexOf('_') + 1;
            if (startIdx > 0) {
                int endIdx = host.indexOf('.', startIdx);
                if (endIdx == -1) {
                    endIdx = host.length();
                }
                try {
                    return Long.parseLong(host.substring(startIdx, endIdx));
                } catch (NumberFormatException e) {
                    return -1;
                }
            }
            return -1;
        }

        private static String getPackageName(String className) {
            int idx = className.lastIndexOf('/');
            if (idx < 0) {
                throw new IllegalArgumentException("Invalid class: " + className);
            }
            return className.substring(0, idx).replace('/', '.');
        }
    }

    private BundleLocator() {
    }
}
