package co.paralleluniverse.fibers.osgi;

import co.paralleluniverse.fibers.instrument.function.ResourceLocator;
import org.osgi.framework.Bundle;
import org.osgi.framework.BundleContext;
import org.osgi.framework.BundleReference;
import org.osgi.framework.wiring.BundleWiring;

import java.net.URL;
import java.security.PrivilegedAction;

import static co.paralleluniverse.common.resource.ClassLoaderUtil.getBestClassLoader;
import static co.paralleluniverse.fibers.instrument.MethodDatabase.JRT_PROTOCOL;
import static java.security.AccessController.doPrivileged;

/**
 * This class is not used directly because {@link ClassLoader#getSystemClassLoader()}
 * might not contain the OSGi Framework classes. We will create this class on demand
 * inside a dynamic classloader, if/when we discover which {@link ClassLoader} the OSGi
 * framework does exist inside.
 */
@SuppressWarnings("unused")
public final class BundleLocator {
    private static final String BUNDLE_PROTOCOL = "bundle";

    public static ResourceLocator getFindResourceOwnerMethod() {
        return BundleLocator::findResourceOwner;
    }

    private static ClassLoader findResourceOwner(ClassLoader cl, String resourceName, URL resource) {
        return doPrivileged((PrivilegedAction<? extends ClassLoader>)() -> findResourceBundle(cl, resourceName, resource));
    }

    private static ClassLoader findResourceBundle(ClassLoader cl, String resourceName, URL resource) {
        if (resource != null) {
            final String protocol = resource.getProtocol();
            if (JRT_PROTOCOL.equals(protocol)) {
                // This resource is from the Java runtime base image.
                return ClassLoader.getPlatformClassLoader();
            } else if (BUNDLE_PROTOCOL.equals(protocol) && (cl instanceof BundleReference)) {
                final long bundleId = parseFelixBundleId(resource);
                final BundleWiring wiring = fetchBundleWiring((BundleReference) cl, bundleId);
                if (wiring != null) {
                    return wiring.getClassLoader();
                }
            } else {
                // Get the first classloader in the hierarchy that can provide this resource.
                return getBestClassLoader(cl, resourceName, resource);
            }
        }
        return cl;
    }

    /**
     *
     * @param resource A bundle:// URL generated by the Felix OSGi framework.
     * @return bundleId for the bundle owning this resource, or -1 if no such bundle.
     */
    private static long parseFelixBundleId(URL resource) {
        // Felix creates bundle:// URLs using the following format:
        //     bundle://<revision-id>:<bundle-classpath-index>/<resource-path>
        // where:
        //     <revision-id> = <framework-uuid>_<bundle-id>.<bundle-revision>
        final String host = resource.getHost();
        final int startIdx = host.indexOf('_') + 1;
        if (startIdx > 0) {
            int endIdx = host.indexOf('.', startIdx);
            if (endIdx == -1) {
                endIdx = host.length();
            }
            try {
                return Long.parseLong(host.substring(startIdx, endIdx));
            } catch (NumberFormatException e) {
                return -1;
            }
        }
        return -1;
    }

    private static BundleWiring fetchBundleWiring(BundleReference ref, long bundleId) {
        final BundleContext context = ref.getBundle().getBundleContext();
        if (context != null) {
            final Bundle targetBundle = context.getBundle(bundleId);
            if (targetBundle != null) {
                return targetBundle.adapt(BundleWiring.class);
            }
        }
        return null;
    }

    private BundleLocator() {
    }
}
