@Library('corda-shared-build-pipeline-steps')
import static com.r3.build.BuildControl.killAllExistingBuildsForJob

killAllExistingBuildsForJob(env.JOB_NAME, env.BUILD_NUMBER.toInteger())

boolean isReleaseBranch = (env.BRANCH_NAME =~ /^release\/.*/)
boolean isRelease = (env.TAG_NAME =~ /^release-.*/)

pipeline {
  agent {
    docker {
        // Our custom docker image
        image "build-zulu-openjdk:17"
        label "standard"
        registryUrl 'https://engineering-docker.software.r3.com/'
        registryCredentialsId 'artifactory-credentials'
        // Used to mount storage from the host as a volume to persist the cache between builds
        args '-v /tmp:/host_tmp'
        alwaysPull true
    }
  }

  parameters {
    booleanParam defaultValue: (isReleaseBranch || isRelease), description: 'Publish artifacts to Artifactory?', name: 'DO_PUBLISH'
  }

  options {
    timestamps()
    timeout(time: 1, unit: 'HOURS')
  }

  environment {
    ARTIFACTORY_CREDENTIALS = credentials('artifactory-credentials')
    CORDA_ARTIFACTORY_USERNAME = "${env.ARTIFACTORY_CREDENTIALS_USR}"
    CORDA_ARTIFACTORY_PASSWORD = "${env.ARTIFACTORY_CREDENTIALS_PSW}"
    CORDA_ARTIFACTORY_REPOKEY = "${isRelease ? 'corda-dependencies' : 'corda-dependencies-dev'}"
    GRADLE_USER_HOME = "/host_tmp/gradle"
  }

  stages {
    stage('Prep') {
        steps {
            // Ensure the dir exists in the mount from the host
            sh 'mkdir -p ${GRADLE_USER_HOME}'
        }
    }

    stage('Compile') {
      steps {
        sh "./gradlew --no-daemon -Pcompilation.allWarningsAsErrors=true -Ptests.failFast=false -Ptests.ignoreFailures=true clean assemble"
      }
    }

    stage('Test') {
      steps {
        sh "./gradlew --no-daemon -Pcompilation.allWarningsAsErrors=true -Ptests.failFast=false -Ptests.ignoreFailures=true testClasses test"
      }
    }

    stage('Publish') {
      when {
        expression { params.DO_PUBLISH }
        beforeAgent true
      }
      steps {
        authenticateGradleWrapper()
        sh "./gradlew --no-daemon -Pcompilation.allWarningsAsErrors=true -Ptests.failFast=false -Ptests.ignoreFailures=true artifactoryPublish"
      }
    }
  }

  post {
    always {
      junit '**/build/test-results/**/*.xml'
    }
    cleanup {
      deleteDir()
    }
  }
}
